site_name: RAGEN
site_url: https://ragen-tutorial.readthedocs.io/
copyright: Copyright © 2025, RAGEN Team

# Theme Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    # - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    # - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Updates: updates.md
  - Quick Start:
    - Installation: quickstart/installation.md
    - Quick Start Guide: quickstart/quick_start.md
  - Configurations:
    - Config Flow: configurations/config_flow.md
    - Config Explanation: configurations/config_exp1.md
  - Practical Guide:
    - Best Practices: practical_guide/best_practices.md
    - FAQ: practical_guide/faq.md
    - Examples:
      - Sokoban: practical_guide/examples/sokoban.md
      - Bi-arm Bandit: practical_guide/examples/bi_arm_bandit.md
      - FrozenLake: practical_guide/examples/frozenlake.md
  - Appendix: appendix.md

# Plugin Configuration
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true
            show_source: true
  - autorefs

# Markdown Extension Configuration
markdown_extensions:
  # Python Markdown Extensions
  - toc:
      permalink: true
  - admonition
  - tables
  - footnotes
  
  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

# Additional Configuration
repo_url: "https://github.com/ZihanWang314/RAGEN"
repo_name: RAGEN