site_name: RAGEN Tutorials
site_url: https://ragen-tutorial.readthedocs.io/
copyright: Copyright © 2025, RAGEN Team
# Theme Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
 - Home: index.md
#  - Getting Started: usage.md

# Plugin Configuration
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true
            show_source: true
  - autorefs

# Markdown Extension Configuration
markdown_extensions:
  # Python Markdown Extensions
  - toc:
      permalink: true
  - admonition
  - tables
  - footnotes
  
  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

# # Additional Configuration
repo_url: "https://github.com/ZihanWang314/RAGEN"  # Set to repository URL if you have a GitHub repository
repo_name: RAGEN  # Set display name if repo_url is set
# version: 0.1.0